name: DEVKING_CHECK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm -v
    - run: npm ci
      continue-on-error: true
    - run: node --check ./app.js